### ISSUE TITLE
New server install refuses to connect via url link or IP address

### ISSUE THREAD

**Issue by EmmaDearest** [Libki/libki-server#233]
**Describe the bug**
Followed the most up to date install instructions on Ubuntu server 20.04, 18.04 and Debian 11. The install process completes with no interrupts, and have tried both the URL and IP options when prompted. Despite many attempts to connect to the server portal, there have been no successful connections. Early on we did connect to a default apache server page, which suggests the auto-installer didn't configure properly. The libki process is confirmed to be running after every install attempt. SSH and ping tests confirm a good connection to the server over the local network. Hardware was connected via ethernet cable to network switch. We tried to install via the most up to date git clone, as well as the last release.

**To Reproduce**
1. Install Libki server
2. attempt to access it via domain url or local ip address

**Expected behavior**
expected to access the admin portal to configure the libki server for client access

**Hardware**
 Installed on a Lenovo Thinkcentre m73

**Additional context**
We had a volunteer well versed in programming and Linux systems look through the install log, and they reached the conclusion that the installer script failed to configure the packages correctly, and that the issue was not related to hardware, OS, or PEBCAK.

**Comment by kylemhall** [comment]
Can you give us the output of the command `ps -aux | grep libki` from your server?

**Comment by EmmaDearest** [comment]
libki@libkiserver:~$ ps -aux | grep libki
avahi        693  0.0  0.0   8612  3628 ?        Ss   00:31   0:00 avahi-daemon: running [libkiserver.local]
root         894  0.0  0.1  19964 11128 ?        S    00:32   0:00 /usr/bin/perl /usr/local/bin/start_server --daemonize --port 3000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /var/log/libki/libki_server.log -- /usr/local/bin/plackup -I /home/libki/libki-server/lib -s Starman --workers 2 --max-requests 50000 -E production -a /home/libki/libki-server/libki.psgi
libki       2027  0.0  0.1  18416  9692 ?        Ss   00:39   0:00 /lib/systemd/systemd --user
libki       2030  0.0  0.0 168844  3472 ?        S    00:39   0:00 (sd-pam)
libki       2043  0.0  0.0   8264  5104 tty1     S+   00:39   0:00 -bash
root        3075  0.0  0.1  13924  8928 ?        Ss   00:49   0:00 sshd: libki [priv]
libki       3174  0.0  0.0  14056  5416 ?        S    00:49   0:00 sshd: libki@pts/0
libki       3175  0.2  0.0   8276  5220 pts/0    Ss   00:49   0:00 -bash
root        3210 62.0  0.9  82656 77316 ?        R    00:50   0:00 /home/libki/libki-server/libki.psgi
libki       3211  0.0  0.0   9084  3584 pts/0    R+   00:50   0:00 ps -aux
libki       3212  0.0  0.0   6432   676 pts/0    R+   00:50   0:00 grep --color=auto libki

and here's the log when the service is ran through the server admin user:
tech@libkiserver:~$ ps -aux | grep libki
avahi        693  0.0  0.0   8612  3628 ?        Ss   00:31   0:00 avahi-daemon: running [libkiserver.local]
root         894  0.0  0.1  19964 11120 ?        S    00:32   0:00 /usr/bin/perl /usr/local/bin/start_server --daemonize --port 3000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /var/log/libki/libki_server.log -- /usr/local/bin/plackup -I /home/libki/libki-server/lib -s Starman --workers 2 --max-requests 50000 -E production -a /home/libki/libki-server/libki.psgi
libki       2027  0.0  0.1  18416  9692 ?        Ss   00:39   0:00 /lib/systemd/systemd --user
libki       2030  0.0  0.0 168844  3472 ?        S    00:39   0:00 (sd-pam)
libki       2043  0.0  0.0   8264  5104 tty1     S+   00:39   0:00 -bash
root        2981  0.0  0.7  66324 60924 ?        R    00:48   0:00 /home/libki/libki-server/libki.psgi
tech        2983  0.0  0.0   6432   720 pts/0    S+   00:48   0:00 grep --color=auto libki

**Comment by kylemhall** [comment]
Have you checked the Libki logs ( /var/log/libki/libki_server.log )? Have you tried launching it directly with script/libki_server.pl?

**Comment by danlerche** [comment]
I was also unable to get the install script to work using Debian 11, Ubuntu 18.04 or 20.04. Server log produced this result. I also noticed the libki mysql database was empty. 

starting new worker 44359 
Use of uninitialized value $dsn in substitution (s///) at /home/libki/libki-server/lib/Libki.pm line 126.
Use of uninitialized value $user in substitution (s///) at /home/libki/libki-server/lib/Libki.pm line 127.
Use of uninitialized value $password in substitution (s///) at /home/libki/libki-server/lib/Libki.pm line 128.
Error while loading /home/libki/libki-server/libki.psgi: Can't locate Image/Magick/Thumbnail/PDF.pm in @INC (you may need to install the Image::Magick::Thumbnail::PDF module) (@INC contains: /home/libki/libki-server/lib /etc/perl /usr/lo>
BEGIN failed--compilation aborted at /home/libki/libki-server/lib/Libki/Controller/API/Jamex/v1_0.pm line 6.
Compilation failed in require at /usr/local/share/perl/5.32.1/Catalyst/Utils.pm line 309.
Compilation failed in require at /home/libki/libki-server/libki.psgi line 4.
BEGIN failed--compilation aborted at /home/libki/libki-server/libki.psgi line 4.
new worker 44359 seems to have failed to start, exit status:512

**Comment by ninfarave** [comment]
> Have you checked the Libki logs ( /var/log/libki/libki_server.log )? Have you tried launching it directly with script/libki_server.pl?

This is the content of the registry that has the installation of EmmaDearest, there is a compile error.
![Libki](https://user-images.githubusercontent.com/4543607/149599002-8cbd6d2e-504d-4e9f-b3dc-5f09feca1c50.png)

**Comment by kylemhall** [comment]
I think the problem is that we are using the Imagemagick perl Module, but that requires imagemagick to be installed on your system prior to the module getting installed. I've updated install.sh, please pull the latest master and give it a try!

**Comment by danlerche** [comment]
I can now run the install script and log into the server in Debian 11. Thanks very much!

**Comment by ninfarave** [comment]
Works for us too.

**Comment by kylemhall** [comment]
Excellent! Thanks for the update!
